name: Clasp Push

on:
  push:
    branches:
      - 'main'

jobs:
  ClaspPush:
    name: Clasp Push
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - name: Pull docker images
        run: make docker_pull_image
      - name: Clasp setup
        run: |
          mkdir root
          echo "$CLASP_JSON" > root/.clasprc.json
          cp .clasp.sample.json .clasp.json
          envsubst < .clasp.json
          cat .clasp.json
        env:
          CLASP_JSON: ${{ secrets.CLASP_JSON }}
          SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
      - name: Deps install
        run: make npm_install
      - name: Transpile and clasp push
        run: make gas_push