name: RunTests

on:
  push:
    branches:
      - 'main'

jobs:
  ClaspPush:
    name: Clasp Push
    on: RunTests
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - name: Pull docker images
        run: make docker_pull_image
      - name: Create .clasprc.json file
        run: mkdir root && echo "$CLASP_JSON" > root/.clasprc.json
        env:
          CLASP_JSON: ${{ secrets.CLASP_JSON }}
      - name: Transpile and clasp push
        run: make ci_clasp_push