name: Reusable workflow example

on:
  workflow_call:
    secrets:
      CR_PAT:
        required: true

jobs:
  RunTests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - name: Pull docker images
        run: make docker_pull_image
      - name: Run tests
        run: make ci_run_tests